@echo off
echo [%time%] Waiting 10 seconds for clean start...
timeout /t 10 /nobreak >nul
echo [%time%] Deleting webhook with NEW token...
"C:\Users\yso\AppData\Local\Programs\Python\Python311\python.exe" -c "import urllib.request; r=urllib.request.urlopen('https://api.telegram.org/bot8772699054:AAGnNYZvKep0BXC6n27uV7LTZ3lm6HEDkig/deleteWebhook?drop_pending_updates=true'); print(r.read().decode())"
echo [%time%] Waiting 3 seconds...
timeout /t 3 /nobreak >nul
echo [%time%] Starting WK Yubi v3.1 (Sonnet 4.6)...
"C:\Users\yso\AppData\Local\Programs\Python\Python311\python.exe" D:\openclaw\bot\wk_bot_v3.py
