@echo off
echo [%time%] Killing python...
taskkill /f /im python.exe >nul 2>&1
echo [%time%] Waiting 5 seconds...
timeout /t 5 /nobreak >nul
echo [%time%] Deleting webhook...
C:\Users\yso\AppData\Local\Programs\Python\Python311\python.exe -c "import urllib.request; r=urllib.request.urlopen('https://api.telegram.org/bot8772699054:AAGnNYZvKep0BXC6n27uV7LTZ3lm6HEDkig/deleteWebhook?drop_pending_updates=true'); print(r.read().decode())"
echo [%time%] Waiting 3 seconds...
timeout /t 3 /nobreak >nul
echo [%time%] Starting WK Yubi v3.3 (Team Relay)...
C:\Users\yso\AppData\Local\Programs\Python\Python311\python.exe D:\openclaw\bot\wk_bot_v3.py
